### ISSUE TITLE
help parameter

### ISSUE THREAD

**Issue by sayedihashimi** [jmprieur/app-provisonning-tool#21]
When running the command with the help parameter (`-h`) passed in, I noticed two issues that we should try to address.

 - If you run help in a folder that doesn't have a project file you get an error
 - If you run help in a folder with a project, the operation will provision azure objects and modify the project. The help command should be idempotent

**Comment by jmprieur** [comment]
Thanks @sayedihashimi
BTW with @jennyf19 and I are in the process of moving the tool to Microsoft.IDentity.Web's repo:
We have a branch with more unit tests: https://github.com/AzureAD/microsoft-identity-web/tree/jennyf/proviTool

**Comment by sayedihashimi** [comment]
@jmprieur thanks for the info. I am starting to work on the doc/blog post for the Visual Studio 16.9 release. Which version of the tool should I use for that doc/blog post?

**Comment by jmprieur** [comment]
For the moment you can use this one, until we have a better version
@jennyf19's priority (and mine) are to productize the tool and have a really great experience. 
Please keep raising issues.
cc: @henrik-me

**Comment by sayedihashimi** [comment]
OK sounds good thanks. I will file other issues that I discover here, whenever we should switch to filing them in the other repo please let me know so I can do that.

**Comment by jmprieur** [comment]
@sayedihashimi 
I cannot repro this one. 

Are you using the latest version? Since we moved to [System.Commandline](https://github.com/jmprieur/app-provisonning-tool/blob/e24228b8c98156e983ca35fcb06f0ad2c6bf8637/src/DotnetTool/ms-identity-app.csproj#L43), the Main is not even called any longer.

Or do you have repro steps?
Be sure to un-install a previously installed version (`dotnet tool uninstall --global ms-identity-app`), build, pack and reinstall.

**Comment by sayedihashimi** [comment]
I was using an old version, will close this now.
